# Generated by Django 3.2.7 on 2021-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default='', max_length=32, verbose_name='邮箱'),
        ),
    ]
