# Generated by Django 3.2.7 on 2021-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户'),
        ),
    ]
