# Generated by Django 3.2.7 on 2021-12-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20211223_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
