// Generated by gencpp from file test/test.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_TEST_H
#define TEST_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <test/testRequest.h>
#include <test/testResponse.h>


namespace test
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::test > {
  static const char* value()
  {
    return "561098128dce463abb21b321b22f8a07";
  }

  static const char* value(const ::test::test&) { return value(); }
};

template<>
struct DataType< ::test::test > {
  static const char* value()
  {
    return "test/test";
  }

  static const char* value(const ::test::test&) { return value(); }
};


// service_traits::MD5Sum< ::test::testRequest> should match
// service_traits::MD5Sum< ::test::test >
template<>
struct MD5Sum< ::test::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::test >::value();
  }
  static const char* value(const ::test::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::testRequest> should match
// service_traits::DataType< ::test::test >
template<>
struct DataType< ::test::testRequest>
{
  static const char* value()
  {
    return DataType< ::test::test >::value();
  }
  static const char* value(const ::test::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::testResponse> should match
// service_traits::MD5Sum< ::test::test >
template<>
struct MD5Sum< ::test::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::test >::value();
  }
  static const char* value(const ::test::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::testResponse> should match
// service_traits::DataType< ::test::test >
template<>
struct DataType< ::test::testResponse>
{
  static const char* value()
  {
    return DataType< ::test::test >::value();
  }
  static const char* value(const ::test::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_TEST_H
