# Generated by Django 3.2.7 on 2021-12-23 12:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, unique=True, verbose_name='用户')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱')),
            ],
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
