// Generated by gencpp from file car/move.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_MOVE_H
#define CAR_MESSAGE_MOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car
{
template <class ContainerAllocator>
struct move_
{
  typedef move_<ContainerAllocator> Type;

  move_()
    : speed(0)
    , angle(0)  {
    }
  move_(const ContainerAllocator& _alloc)
    : speed(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef uint8_t _speed_type;
  _speed_type speed;

   typedef uint16_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::car::move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car::move_<ContainerAllocator> const> ConstPtr;

}; // struct move_

typedef ::car::move_<std::allocator<void> > move;

typedef boost::shared_ptr< ::car::move > movePtr;
typedef boost::shared_ptr< ::car::move const> moveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car::move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car::move_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car::move_<ContainerAllocator1> & lhs, const ::car::move_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car::move_<ContainerAllocator1> & lhs, const ::car::move_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car::move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car::move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "597e65a9308a300a178585c76dd2bae5";
  }

  static const char* value(const ::car::move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x597e65a9308a300aULL;
  static const uint64_t static_value2 = 0x178585c76dd2bae5ULL;
};

template<class ContainerAllocator>
struct DataType< ::car::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car/move";
  }

  static const char* value(const ::car::move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car::move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 speed\n"
"uint16 angle\n"
;
  }

  static const char* value(const ::car::move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car::move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car::move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car::move_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MESSAGE_MOVE_H
