# Generated by Django 3.2.7 on 2021-12-25 08:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, unique=True, verbose_name='用户')),
                ('rule', models.IntegerField(choices=[(1, '订单管理'), (2, '订单管理,管理员管理'), (3, '订单管理,管理员管理,权限修改')], verbose_name='权限')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], verbose_name='状态')),
            ],
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
